version: '3.4'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "is4"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postrges_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:7.16.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672' 
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: "redis:latest"
    container_name: 'redis'
    restart: always
    ports:
      - "6379:6379"
        
volumes:
  postrges_volume:
    external: false
  elastic_volume:
    external: false
