version: '3.4'

services:

  blazor:
    build: EM.UI.Blazor
    ports:
      - "7250:443"
      
  webapi:
    build: EM.WebApi.Core
    ports:
      - "7890:7890"

  is4:
    build: EM.IdentityServer4
    ports:
      - "7890:7890"

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "is4"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  is4:
    build: EM.IdentityServer4
    ports:
      - "10001:10001"
    environment:
      ConnectionStrings__PostgresConnection: "Server=localhost;Port=5432;Database=is4;Username=user;Password=password"
      
volumes:
  postgres-volume:
    external: false