version: '3.4'

services:

  blazor:
    build:
      context: ./
      dockerfile: EM.UI.Blazor/Dockerfile
    ports:
      - "7250:443"
      
  webapi:
    build: 
      context: ./
      dockerfile: EM.WebApi.Core/Dockerfile
    environment:
      ElasticsearchOptions__Uri: "http://elasticsearch:9200"
    ports:
      - "7890:7890"

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "is4"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  is4:
    build: EM.IdentityServer4
    ports:
      - "10001:10001"
    environment:
      ConnectionStrings__PostgresConnection: "Server=postgres;Port=5432;Database=is4;Username=user;Password=password"
      
  elasticsearch:
    image: elasticsearch:7.16.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data

volumes:
  postgres-volume:
    external: false
  elastic_volume:
    external: false