version: '3.4'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "is4"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postrges_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        
volumes:
  postrges_volume:
    external: false
