version: '3.4'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "is4"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postrges_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:7.16.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.16.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672' 
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq

  redis:
    image: "redis:latest"
    container_name: 'redis'
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  is4:
    build: EM.IdentityServer4
    # image: registry.gitlab.com/chil84/otusaspnetcorea02team02/is4:0.0.1
    restart: always
    depends_on:
      - postgres
    ports:
      - "10001:10001"
    environment:
      ConnectionStrings__PostgresConnection: "Server=postgres;Port=5432;Database=is4;Username=user;Password=password"

  fakedata:
    build: 
      dockerfile: Dockerfile.FakeData
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "5118:5118"
    environment:
      RabbitMqOptions__HostName: "rabbitmq"

  logstash:
    build: 
      dockerfile: ${PWD}/Dockerfile.logstash
      context: ${PWD}/
    restart: always
    depends_on:
      - elasticsearch
      - postgres
    environment:
      - LOGSTASH_JDBC_URL=jdbc:postgresql://postgres:5432/offers
      - LOGSTASH_JDBC_DRIVER=org.postgresql.Driver
      - LOGSTASH_JDBC_DRIVER_JAR_LOCATION=/usr/share/logstash/logstash-core/lib/jars/postgresql.jar
      - LOGSTASH_JDBC_USERNAME=user
      - LOGSTASH_JDBC_PASSWORD=password
      - LOGSTASH_ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes: 
      - ./postgres-jdbc-input.conf:/usr/share/logstash/pipeline/logstash.conf
        
volumes:
  postrges_volume:
    external: false
  elastic_volume:
    external: false
  rabbitmq_volume:
    external: false
  redis_volume:
    external: false
