FROM docker.elastic.co/logstash/logstash:7.3.2

# # install dependency
# RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-jdbc
# RUN /usr/share/logstash/bin/logstash-plugin install logstash-filter-aggregate
# RUN /usr/share/logstash/bin/logstash-plugin install logstash-filter-jdbc_streaming
# RUN /usr/share/logstash/bin/logstash-plugin install logstash-filter-mutate

# copy lib database jdbc jars
COPY ./123/postgresql-42.4.1.jar /usr/share/logstash/logstash-core/lib/jars/postgresql.jar
COPY statement.sql /usr/share/logstash/logstash-core/lib/jars/statement.sql